[package]
name = "cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }

[[bin]]
name = "ubiq"
path = "src/main.rs"
